IITBPortal/IITBPortal/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^index/',include('index.urls')),
    url(r'^admin/', admin.site.urls),
    #url(r'^',include('index.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

IITBPortal/index/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

app_name = 'index'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^refresh_feed/$', views.refresh_feed, name='refresh_feed'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/profile_pic/$', views.update_profile_pic, name='update_profile_pic'),
    url(r'^profile/update_profile/$', views.update_profile, name='update_profile'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/first_login/$', views.first_login, name='first_login'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^course/$', views.registered_courses, name='registered_courses'),
    url(r'^course/(?P<course_id>[0-9]+)/$', views.course, name='course'),

    url(r'^course/(?P<course_id>[0-9]+)/add_topic/$', views.add_topic, name='add_topic'),

    url(r'^profile/update_profile/$', views.update_profile, name='update_profile'),
    url(r'^profile/add_interests/$', views.add_interests, name='add_interests'),
    url(r'^profile/update_interests/$', views.update_interests, name='update_interests'),
    url(r'^all_courses/$', views.all_courses, name='all_courses'),
    url(r'^course_info/(?P<course_id>[0-9]+)/$', views.course_info, name='course_info'),
    url(r'^register_course/(?P<course_id>[0-9]+)/$', views.register_course, name='register_course'),
    url(r'^update_topic_assignment/(?P<topic_id>.*)/$', views.add_assignment, name='add_assignment'),
    url(r'^update_topic_material/(?P<topic_id>.*)/$', views.add_course_material, name='add_course_material'),
    url(r'^take_quiz/(?P<quiz_id>.*)/$', views.take_quiz, name='take_quiz'),
    url(r'^update_topic_resourse/(?P<topic_id>.*)/$', views.add_resourse, name='add_resourse'),

    url(r'^course/add_quiz/(?P<topic_id>[0-9]+)/$', views.add_quiz, name='add_quiz'),

    url(r'^course/add_another_question/(?P<quiz_id>[0-9]+)/$', views.add_another_question, name='add_another_question'),

    url(r'^course/take_quiz/(?P<quiz_id>[0-9]+)/$', views.take_quiz, name='take_quiz'),
    url(r'^course/add_question/(?P<topic_id>[0-9]+)/(?P<quiz_id>[0-9]+)/$', views.add_question, name='add_question'),

    url(r'^course/evaluate_quiz/(?P<quiz_id>[0-9]+)/$', views.evaluate_quiz, name='evaluate_quiz'),

    url(r'^course/result/(?P<quiz_id>[0-9]+)/$', views.result, name='result'),

]

IITBPortal/index/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from django.conf import settings
from datetime import datetime
# Create your models here.

class Student(models.Model):
    user = models.ForeignKey(User)
    email_id = models.EmailField(max_length=150,default='')
    login_id = models.CharField(max_length=100,default='')
    first_name = models.CharField(max_length=250,default='')
    last_name = models.CharField(max_length=250,default='')
    phone = models.CharField(max_length=250,default='')
    university = models.CharField(max_length=250,default='')
    city = models.CharField(max_length=250,default='')
    profile_pic = models.FileField(default='blank-user.jpg')
    is_professor = models.BooleanField(default=False)
    def __str__(self):
        return self.first_name + ' ' + self.last_name + ' : ' + self.login_id

class Course(models.Model):
    course_code = models.CharField(max_length=20,default="")
    course_name = models.CharField(max_length=250,default="")
    course_info = models.CharField(max_length=500, default='')
    all_students = models.ManyToManyField(Student)

    def __str__(self):
        return self.course_code + ' : ' + self.course_name


class Topic(models.Model):
    course = models.ForeignKey(Course)
    topic_name = models.CharField(max_length=100, default='')
    topic_info = models.CharField(max_length=500, default='')

    def __str__(self):
        return self.topic_name


class Assignment(models.Model):
    assignment_name = models.CharField(max_length=250, default='')
    assignment_info = models.CharField(max_length=500, default='')
    parent_topic = models.ForeignKey(Topic, on_delete=models.CASCADE, default=None)
    assignment_content_file = models.FileField(null=True, blank=True,)
    date_added = models.DateTimeField(default=datetime.now)
    deadline = models.DateTimeField(default=datetime.now)
    submissions = models.ManyToManyField(
        User,
    )

    def __str__(self):
        return self.assignment_name + ' : ' + self.parent_topic.topic_name


class Course_Material(models.Model):
    course_material_name = models.CharField(max_length=250)
    course_material_info = models.TextField()
    parent_topic = models.ForeignKey(Topic, on_delete=models.CASCADE, default=None)
    course_content_file = models.FileField(null=True, blank=True,)

    def __str__(self):
        return self.course_material_name + ' : ' + self.parent_topic.topic_name


class Interest(models.Model):
    interest_name = models.CharField(max_length=250, default='')
    all_students = models.ManyToManyField(Student)

    def __str__(self):
        return self.interest_name


class Quiz(models.Model):
    parent_topic = models.ForeignKey(Topic, default=None)

    quiz_name = models.CharField(max_length=100, default='')
    quiz_info = models.CharField(max_length=500, default='')
    quiz_attempted = models.BooleanField(default=False)

    def __str__(self):
        return self.quiz_name

class Grade(models.Model):
    parent_student = models.ForeignKey(Student, default=None)
    parent_quiz = models.ForeignKey(Quiz, default=None)
    quiz_attempted = models.BooleanField(default=False)
    #evaluation scheme +4 -1
    total_marks = models.IntegerField(default=100)
    marks_obtained = models.IntegerField(default=0)

    def __str__(self):
        return self.parent_quiz.quiz_name + " marks"

class Question(models.Model):
    parent_quiz = models.ForeignKey(Quiz, default=None)
    question_text = models.CharField(max_length=500, default='')
    is_subjective = models.BooleanField(default=False)
    option1 = models.CharField(max_length=100,default='')
    option2 = models.CharField(max_length=100, default='')
    option3 = models.CharField(max_length=100, default='')
    option4 = models.CharField(max_length=100, default='')
    correct_answer = models.CharField(max_length=20, default='')
    answer_given_by_student = models.CharField(max_length=20, default='')

    def __str__(self):
        return str(self.id) + ' ' + self.parent_quiz.quiz_name + ' ' + self.parent_quiz.parent_topic.topic_name + ' '+ self.question_text


class Answer_record(models.Model):
    parent_student = models.ForeignKey(Student,default=None)
    parent_question = models.ForeignKey(Question,default=None)
    ans_given = models.CharField(max_length=20,default='')

    def __str__(self):
        return self.parent_question.question_text


class News_feed(models.Model):

    image_url = models.CharField(max_length=500,default="")
    href_url = models.CharField(max_length=500, default="")
    topic = models.CharField(max_length=500,default="")
    desc = models.CharField(max_length=1000, default="")
    date = models.CharField(max_length=100, default="")
    tag = models.CharField(max_length=500, default="")
    my_tag = models.CharField(max_length=500, default="")

    def __str__(self):
        return self.topic

IITBPortal/index/templates/index/add_assignment.html
{% extends 'index/base.html' %}

{% block title %}Add assignment{% endblock %}

{% block body %}
<form class="form-horizontal" action="{% url 'index:add_assignment' topic.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div datatype="">{{ field }}</div>
    </div>
    {% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Add</button>
        </div>
    </div>
</form>
{% endblock %}

IITBPortal/index/templates/index/add_question.html
{% extends 'index/base.html' %}

{% block title %}Add Question{% endblock %}

{% block body %}
<div class="container">
<form class="form-horizontal" action="{% url 'index:add_question' topic_id=topic.id quiz_id=quiz.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group">
      <label for="question_text" class="control-label col-sm-2">Question</label>
      <div class="col-sm-10" >
        <input type="text" class="form-control" name="question_text" id="question_text">
      </div>
    </div>
    <br><br>
    <h5 style="margin-left: 115px;font-weight:bold"><strong>Type</strong></h5>
    <div class="col-sm-10" style="margin-left: 178px">
    <div class="radio">
        <label><input type="radio" name="is_subjective" value="objective">Objective</label>
    </div>
    <div class="radio">
        <label><input type="radio" name="is_subjective" value="subjective">Subjective</label>
    </div>
    </div>
    <br><br<br><br>
    <br><br>
    <div class="form-group">
      <label class="control-label col-sm-2">option1</label>
      <div class="col-sm-10" >
        <input type="text" class="form-control" name="option1">
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2">option2</label>
        <div class="col-sm-10" >
            <input type="text" class="form-control" name="option2" >
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2">option3</label>
      <div class="col-sm-10" >
        <input type="text" class="form-control" name="option3">
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2">option4</label>
        <div class="col-sm-10" >
        <input type="text" class="form-control" name="option4">
        </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2">Correct Answer </label>
        <div class="col-md-4 selectContainer">
        <div class="input-group">
        <select name="correct_answer" class="form-control selectpicker" >
            <option>option1</option>
            <option>option2</option>
            <option>option3</option>
            <option>option4</option>
        </select>
      </div>
    </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Add Question</button>
        </div>
    </div>
</form>
</div>
{% endblock %}

IITBPortal/index/templates/index/add_quiz.html
{% extends 'index/base.html' %}

{% block title %}Add Quiz{% endblock %}

{% block body %}
<form class="form-horizontal" action="{% url 'index:add_quiz' topic.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div datatype="">{{ field }}</div>
    </div>
    {% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Add Quiz</button>
        </div>
    </div>
</form>
{% endblock %}

IITBPortal/index/templates/index/add_resourse.html
{% extends 'index/base.html' %}

{% block title %}Add Course Material{% endblock %}

{% block body %}
<form class="form-horizontal" action="{% url 'index:add_resourse' topic.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div datatype="">{{ field }}</div>
    </div>
{% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Add</button>
        </div>
    </div>
</form>
{% endblock %}

IITBPortal/index/templates/index/add_topic.html
{% extends 'index/base.html' %}

{% block title %}Add Topic{% endblock %}

{% block body %}
<form class="form-horizontal" action="{% url 'index:add_topic' course.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div datatype="">{{ field }}</div>
    </div>
{% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Add</button>
        </div>
    </div>
</form>
{% endblock %}

IITBPortal/index/templates/index/all_courses.html
{% extends 'index/base.html' %}
{% block title %}courses{% endblock %}
{% block all_active %}class="active"{% endblock %}
{% block body %}

<html>
    <style>
      .info {
  background-color: #fff;
  padding: 10px;

  border: 1px solid #000000;
  border-radius: 20px;
  width: 80%;
}

.info:hover {
	background-color: #ccc;
	border-color: green;

}

.info:active {

  top: +12px;
}
    </style>

 </html>


    <h1>List of all courses</h1><br>
    <!--<ul>
        {% for course in students.courses_set.all %}
        <li><a href="{% url 'index:course' course.id %}">
            {{ course.course_code }} - {{ course.course_name }}
            </a>
        </li>

        {% endfor %}
    </ul>-->
    <ul>
    {% if courses %}
    {% for course in courses %}
        <div class="info">
            <a href="{% url 'index:course_info' course.id %}"><h1>{{ course.course_code }} - {{ course.course_name }}</h1></a>
            {{ course.course_info }}
        </div>
        <br><br>
    {% endfor %}
    {% endif %}
    </ul>
{% endblock %}

IITBPortal/index/templates/index/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Title Block{% endblock %}</title>
    <meta name="description" content="Free Bootstrap Theme by BootstrapMade.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/imagehover.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/style.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js">        </script>
    <script type="text/javascript" src="/static/admin/js/jquery.min.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.min.js"></script>
    <script type="text/javascript" src="/static/admin/js/calendar.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>

</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'index:index' %}">IITB<span>Portal</span></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li {% block home_active %}{% endblock %}><a href="{% url 'index:index' %}">Home</a></li>
          <li {% block courses_active %}{% endblock %}><a href="{% url 'index:registered_courses' %}">My Courses</a></li>
          <li {% block all_active %}{% endblock %}><a href="{% url 'index:all_courses' %}">All Courses</a></li>
          <!--<li {% block profile_active %}{% endblock %}><a href="{% url 'index:profile' %}">My Profile</a></li>-->
          <li><a href="{% url 'index:logout_user' %}" data-target="" data-toggle="modal">Logout</a></li>
          <li class="btn-trial"><a href="{% url 'index:profile' %}">{{ student.first_name }} {{ student.last_name }}</a></li>
        </ul>
        </div>
      </div>
    </nav>
    <br><br><br><br>

{% block body %}
{% endblock %}

</body>
</html>

    <!--/ Navigation bar-->

IITBPortal/index/templates/index/login.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<link rel="stylesheet" type="text/css" href="{% static 'index/login_style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'index/login_style.js' %}" />

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<div class="login-page">
    <div class="form">

    <form class="login-form" role="form" action="{% url 'index:login_user'%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <input type="text" placeholder="username" id="id_username" maxlength="30" name="username"/>
      <input type="password" placeholder="password" id="id_password" maxlength="30" name="password"/>
      <button type="submit">login</button>
      <p class="message">Not registered yet? <a href="{% url 'index:register' %}">Create an account</a></p>
    </form>
  </div>
</div>

IITBPortal/index/templates/index/profile.html
{% extends 'index/base.html' %}
{% block title %}Profile{% endblock %}
{% block profile_active %}class= "active"{% endblock %}

{% block body %}


<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">

    <!-- Left Column -->
    <div class="w3-third">

      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <img src="{{ student.profile_pic.url }}" align="middle" style="width:50%" alt="http://www.stallerdental.com/wp-content/uploads/2016/12/user-icon.png">
          <br><br>
          <form class="form-horizontal" role="form" action="{% url 'index:update_profile_pic' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div style="text-align: center;">
                                <button type="submit" class="btn btn-success">Update Profile pic</button>
                            </div>
                        </div>
                    </form>
          <br>
        </div>

        <div class="w3-container">

          <p><i class="fa fa-user fa-fw w3-margin-right w3-large w3-text-teal"></i>{{ student.first_name }} {{ student.last_name }}</p>
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>
          {% if student.is_professor %}
              Professor
          {% else %}
              Student
          {% endif %}
          </p>
          <p><i class="fa fa-university fa-fw w3-margin-right w3-large w3-text-teal"></i>{{ student.university }}</p>
          <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i>{{ student.city }}</p>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i>{{ student.email_id }}</p>
          <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i>{{ student.phone }}</p>
          <hr>
          <form class="form-horizontal" role="form" action="{% url 'index:update_profile' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div style="text-align: center;">
                                <button type="submit" class="btn btn-success">Update Profile</button>
                            </div>
                        </div>
                    </form>

          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Interests</b></p>
          {% for interest in student.interest_set.all %}
            <p>{{ interest.interest_name }}</p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:100%">100%</div>
          </div>
            {% endfor %}<br>
          <form class="form-horizontal" role="form" action="{% url 'index:add_interests' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div style="text-align: center;">
                                <button type="submit" class="btn btn-success">Update Interests</button>
                            </div>
                        </div>
                    </form>
          <br>
          <!--<p class="w3-large w3-text-theme"><b><i class="fa fa-globe fa-fw w3-margin-right w3-text-teal"></i>Languages</b></p>-->
          <!--<p>English</p>-->
          <!--<div class="w3-light-grey w3-round-xlarge">-->
            <!--<div class="w3-round-xlarge w3-teal" style="height:24px;width:100%"></div>-->
          <!--</div>-->
          <!--<p>Spanish</p>-->
          <!--<div class="w3-light-grey w3-round-xlarge">-->
            <!--<div class="w3-round-xlarge w3-teal" style="height:24px;width:55%"></div>-->
          <!--</div>-->
          <!--<p>German</p>-->
          <!--<div class="w3-light-grey w3-round-xlarge">-->
            <!--<div class="w3-round-xlarge w3-teal" style="height:24px;width:25%"></div>-->
          <!--</div>-->
          <br>
        </div>
      </div><br>

    <!-- End Left Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-twothird">


      <div class="w3-container w3-card-2 w3-white">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Progress Report</h2>

        {% for course in student.course_set.all %}
        <div class="w3-container">
          <h5 class="w3-opacity"><b>{{ course.course_code }} - {{ course.course_name }}</b></h5>
            {% for topic in course.topic_set.all %}
            {% for quiz in topic.quiz_set.all %}

            <h6 class="w3-text-teal"><i class="fa fa-paper-plane-o fa-fw w3-margin-right"></i><a href="{% url 'index:evaluate_quiz' quiz.id %}">{{ quiz.quiz_name }}</a></h6>
            {% endfor %}
            {% endfor %}
            <hr>
        </div>
        {% endfor %}
      </div>

    <!-- End Right Column -->
    </div>

  <!-- End Grid -->
  </div>

  <!-- End Page Container -->
</div>


{% endblock %}

IITBPortal/index/templates/index/quiz_result.html
{% extends 'index/base.html' %}

{% block title %}Quiz Result{% endblock %}

{% block body %}
<h2>Here is the question wise evaluation of {{ quiz.quiz_name }}</h2>
<!--check_and_show_marks view to be implemented-->
{% if grade %}
{% for question in questions %}
<div class="container">
    <div class = "panel panel-warning">
       <div class = "panel-heading">
          <h3 class = "panel-title"><b>{{ question.question_text }}</b></h3>
       </div>
       <div class = "panel-body">
           1) {{ question.option1 }}<br>
           2) {{ question.option2 }}<br>
           3) {{ question.option3 }}<br>
           4) {{ question.option4 }}<br>
    <br>
    {% if grade.quiz_attempted %}
    {% for rec in question.answer_record_set.all %}
    {% if rec.parent_student == student %}
    <h4 style="color: blue">Correct Answer is:- {{ question.correct_answer }}</h4>
    <h4 style="color: blue"> Your Answer is:-
    {% if rec.ans_given %}
        {{ rec.ans_given }}<br>
        {% if rec.ans_given == question.correct_answer %}
    <h4 style="color: blue">Result:- <font color="green">Correct Answer! , +4 </font></h4>
        {% else %}
        <h4 style="color: blue">Result:- <font color="red">Wrong Answer! , -1 </font></h4>
        {% endif %}
    {% else %}
        No answer given by you! , +0
    {% endif %}
    </h4>
    {% endif %}
    {% endfor %}
    {% endif %}
       </div>
    </div>
</div>
{% endfor %}

<div class="container" style="background-color: #fcfc1e">
    <h3>Here are final marks</h3>
    <h4>Marks obtained:- <font color="blue">{{ grade.marks_obtained }}</font> out of <font color="blue">{{ grade.total_marks }} </font></h4>
</div>
{% else %}
<div class="container" style="background-color: #fcfc1e">
    <h4 style="color: red">You haven't attempted the quiz</h4>
</div>
{% endif %}
<br><br><br><br><br><br><br><br>
{% endblock %}

IITBPortal/index/templates/index/register.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<link rel="stylesheet" type="text/css" href="{% static 'index/login_style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'index/login_style.js' %}" />

{% if error_message %}
  <p><strong>{{ error_message }}</strong></p>
{% endif %}

<div class="login-page">
  <div class="form">
    <form class="login-form" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <h4>First Name</h4>
      <input type="text" placeholder="first name" name="first_name"/>
      <h4>Last Name</h4>
      <input type="text" placeholder="last name" name="last_name"/>
      <h4>Username</h4>
      <input type="text" placeholder="create a username" id="id_username" maxlength="30" name="username"/>
      <h4>Password</h4>
      <input type="password" placeholder="password" name="password"/>
      <button type="submit">Sign Up</button>
      <p class="message"><h4  >Already registered? <a href="{% url 'index:login_user' %}"><br>Sign In</h4></a></p>
    </form>
  </div>
</div>

IITBPortal/index/templates/index/update_interests.html
{% extends 'index/base.html' %}
{% block title %}Update Interest{% endblock %}

{% block body %}
<form class="form-horizontal" action="{% url 'index:update_interests'%}" method="post" enctype="multipart/form-data">
    {% csrf_token %}


<div class="form-group">
                    <label class="col-md-4 control-label">Select your interests*</label>
                    <div class="col-md-4">
                        {% for interest in INTERESTS %}
                        <div class="check">
                            <label>
                                <input type="checkbox" value="{{ interest }}" name="interest_list"/>{{ interest }}
                            </label>
                        </div>
                        {% endfor %}
                    </div>
                </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Update Interests</button>
        </div>
    </div>
</form>
{% endblock %}